header = "renderable"

[renderable.model]
layout = 0b11111101
mask = 0b1111
shader = "config/shaders/SolidCircleShader.toml"

[renderable]
# condensed P-transform (2) | condensed RS-transform (4) | RGBA color (4) | vertex position + local bounds position (4)
vertices = [
	0.0, 0.0,					1.0, 0.0, 0.0, 1.0,		1.0, 1.0, 1.0, 1.0,		 1.0,  1.0,  1.0,  1.0,
	0.0, 0.0,					1.0, 0.0, 0.0, 1.0,		1.0, 1.0, 1.0, 1.0,		-1.0,  1.0, -1.0,  1.0,
	0.0, 0.0,					1.0, 0.0, 0.0, 1.0,		1.0, 1.0, 1.0, 1.0,		-1.0, -1.0, -1.0, -1.0,
	0.0, 0.0,					1.0, 0.0, 0.0, 1.0,		1.0, 1.0, 1.0, 1.0,		 1.0, -1.0,  1.0, -1.0
]
num_vertices = 4
indices = [0, 1, 2, 3]
