header = "renderable"

[renderable.model]
layout = 0b11010100
mask = 0b1111

[renderable]
# texture slot | vertex position | texture coordinate | RGBA color
vertices = [
	-1.0, -0.5, -0.5, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0,
	-1.0,  0.5, -0.5, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0,
	-1.0,  0.5,  0.5, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0,
	-1.0, -0.5,  0.5, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0
]
num_vertices = 4
indices = [
	0, 1, 2,
	2, 3, 0
]
