[window]
width = 1440
height = 1080
gl_clear_color = [0.08, 0.08, 0.08, 0.0]

[rendering]
max_texture_slots = 32
standard_vertex_pool_size = 2048
standard_index_pool_size = 1024
rect_renderable = "config/RectRenderable.toml"
atlas_renderable = "config/AtlasRenderable.toml"
