header = "renderable"

[renderable.model]
layout = 0b110101111101
mask = 0b111111
shader = "config/SolidCircleShader.toml"

[renderable]
# condensed P-transform (2) | condensed RS-transform (4) | RGBA outer color (4) | vertex position (2) | point size, inner radius (2) | RGBA inner color (4)
vertices = [
#	0.0, 0.0,					1.0, 0.0, 0.0, 1.0,			1.0, 1.0, 1.0, 1.0,		0.0, 0.0,					2.0, 0.3,				0.0, 0.0, 0.0, 0.0
]
num_vertices = 0
indices = []
